use_frameworks!
workspace 'ResourceApp'

target 'ResourceApp' do
  platform :ios, '11.0'
  project 'ResourceApp'

  pod 'SWRevealViewController'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
