//
//  HeaderPrinter.swift
//  R.swift
//
//  Created by Mathijs Kadijk on 06-10-16.
//  From: https://github.com/mac-cain13/R.swift
//  License: MIT License
//

import Foundation

/// Prints a static header for the generated file
struct HeaderPrinter: SwiftCodeConverible {
  let swiftCode = [
    "//",
    "// This is a generated file, do not edit!",
    "// Generated by R.swift, see https://github.com/mac-cain13/R.swift",
    "//",
  ].joined(separator: "\n")
}
