use_frameworks!
workspace 'RswiftExamples'

def rswiftlib
  pod 'R.swift.Library', :git => 'https://github.com/mac-cain13/R.swift.Library.git' # for CI builds
#  pod 'R.swift.Library', :path => '../../R.swift.Library' # for development
end

target 'ResourceApp' do
  platform :ios, '9.0'
  project 'ResourceApp/ResourceApp'

  pod 'SWRevealViewController'

  rswiftlib
end

target 'ResourceAppTests' do
  platform :ios, '9.0'
  project 'ResourceApp/ResourceApp'

  pod 'SWRevealViewController'

  rswiftlib
end

target 'ResourceApp-watchOS-Extension' do
  platform :watchos, '2.2'
  project 'RwatchApp/RwatchApp'

  rswiftlib
end
