// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift

import Foundation
import Rswift
import UIKit

struct R {
  struct image {
    static let watchIcon = ImageResource(bundle: _R.hostingBundle, name: "watchIcon")
    
    static func watchIcon(`_`: Void) -> UIImage? {
      return UIImage(resource: R.image.watchIcon)
    }
  }
}

struct _R {
  static let hostingBundle = NSBundle(identifier: "nl.mathijskadijk.ResourceApp")
}