name: Test

on:
  push:
    branches: [ "6" ]
  pull_request:
    branches: [ "6" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
